name: 'CloudFormation: Read parameters'
description: |
  This command reads parameters with a specific path prefix from SSM Parameter Store into outputs for following steps. This allows you to use these values as environment variables in subsequent steps. For example, if you have a parameter with the name "/Project/Upload/ArtifactBucket", this would be set as outputs.project_upload_artifact_bucket. You can use then use these as environment variables in later steps.
  
  To generate the variable key, we replace all slashes with underscores, 
  strip any "special characters" ("-" for example) and 
  convert camel-case to snake-case.
inputs:
  path:
    required: true
    description: |
      The path prefix for parameters
runs:
  using: docker
  image: firstclasspostcodes/github-action:latest
  args:
    - /command/cloudformation/read-parameters/action.sh
    - ${{inputs.path}}