name: 'CloudFormation: Read parameters'
description: |
  This command reads parameters with a specific path prefix from SSM Parameter Store and outputs all matching parameters in kebab case.
inputs:
  path:
    required: true
    description: |
      The path prefix for parameters
runs:
  using: 'node12'
  main: 'dist/index.js'
