on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test read parameters
    steps:
      - name: Test Read Parameters
        id: read-parameters
        uses: firstclasspostcodes/github-action/cloudformation/read-parameters@v0.0.6
        with:
          path: '/env/to/path'